# Generated by Django 2.2.4 on 2020-09-24 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bidinterpreter', '0002_auto_20200804_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bidinterpreter.BidDoc'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
