# Generated by Django 2.2.4 on 2020-10-01 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bidinterpreter', '0003_auto_20200924_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='biddoc',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='biddoc',
            name='text',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='biddoc',
            name='word_coords',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bidinterpreter.BidDoc'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
    ]
