# Generated by Django 2.2.4 on 2020-12-20 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bidinterpreter', '0004_auto_20201001_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deal',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='biddoc',
            name='status',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
