# Generated by Django 2.2.4 on 2021-03-14 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bidinterpreter', '0005_auto_20201220_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidDocStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_doc_name', models.CharField(max_length=250)),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bid',
            name='date_received',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='biddoc',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='biddoc',
            name='word_coords',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='deal_name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.CreateModel(
            name='DealInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('unique_id', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField(blank=True, default=-1)),
                ('user_group', models.CharField(blank=True, max_length=255)),
                ('user_permission', models.IntegerField(default=0)),
                ('viewed', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidinterpreter.Deal')),
            ],
            options={
                'unique_together': {('deal', 'email')},
            },
        ),
    ]
