# Generated by Django 2.2.4 on 2021-03-15 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidinterpreter', '0006_auto_20210314_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='company_name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
