# Generated by Django 3.1.6 on 2021-04-28 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bidinterpreter', '0007_bid_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='biddocstats',
            name='biddoc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bidinterpreter.biddoc'),
        ),
        migrations.AddField(
            model_name='biddocstats',
            name='results',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biddoc',
            name='word_coords',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
