# Generated by Django 3.1.6 on 2021-05-08 21:09

from django.db import models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidinterpreter', '0008_auto_20210428_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biddoc',
            name='word_coords',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biddocstats',
            name='results',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
