# Generated by Django 3.2.3 on 2021-05-21 23:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bidinterpreter', '0009_auto_20210508_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
